# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
# Modified by Ric Harvey <ric@squarecows.com>
# Now runs with standard Postgres and Redis images
# Plus Mailhog for local testing

version: '2'
services:
  postgresql:
    image: docker.io/postgres:16
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=bitnami123
      - POSTGRES_DB=bitnami_discourse
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/data'
  discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      postgresql:
         condition: service_healthy
      redis:
         condition: service_started
    environment:
      - BITNAMI_DEBUG=true
      - DISCOURSE_ENV-development
      - DISCOURSE_HOST=localhost
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=postgres
      - DISCOURSE_DATABASE_PASSWORD=bitnami123
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_EMAIL=discourse@local.host
      - DISCOURSE_SMTP_HOST=mailhog
      - DISCOURSE_SMTP_PORT=1025
      - DISCOURSE_SMTP_ENABLE_TLS:false
      - DISCOURSE_S3_REGION=eu-west-1
  sidekiq:
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=localhost
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=postgres
      - DISCOURSE_DATABASE_PASSWORD=bitnami123
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_SMTP_HOST=mailhog
      - DISCOURSE_SMTP_PORT=1025
      - DISCOURSE_SMTP_ENABLE_TLS:false
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    depends_on:
      - discourse
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
